;;; SPDX-FileCopyrightText: 2020 Adam R. Nelson <adam@nels.onl>
;;;
;;; SPDX-License-Identifier: MIT

(define-syntax chain
  (syntax-rules ell1 ()
    ((_ initial-value) initial-value)
    ((_ initial-value (step ell1) ell1)
     (chain initial-value _ ... (step ell1) ell1))
    ((_ initial-value placeholder (step ell1) ell1)
     (chain initial-value placeholder ... (step ell1) ell1))
    ((_ initial-value placeholder ellipsis (first-step ell1) (next-step ell1) ell1)
     (let ()
       (define-syntax %chain
         (syntax-rules ell2 (placeholder ellipsis)
           ; (_ in-step out-step in-vars out-vars in-steps out-steps)
           ((_ () () () ((var) ell2) () (step ell2 last-step))
            (let* ((var step) ell2) last-step))
           ((_ () () () (vars ell2) () (step ell2 last-step))
            (let*-values ((vars step) ell2) last-step))
           ((_ () () () out-vars (step . in-steps) out-steps)
            (%chain step () () out-vars in-steps out-steps))
           ((_ () step () (out-vars ell2) in-steps (out-steps ell2))
            (%chain () () () (out-vars ell2 ignored) in-steps (out-steps ell2 step)))
           ((_ () step vars (out-vars ell2) in-steps (out-steps ell2))
            (%chain () () () (out-vars ell2 vars) in-steps (out-steps ell2 step)))
           ((_ (placeholder ellipsis) (step ell2) () (out-vars ell2) in-steps (out-steps ell2))
            (%chain () () () (out-vars ell2 chain-rest-var) in-steps (out-steps ell2 (apply step ell2 chain-rest-var))))
           ((_ (placeholder ellipsis) (step ell2) (vars ell2) (out-vars ell2) in-steps (out-steps ell2))
            (%chain () () () (out-vars ell2 (vars ell2 . chain-rest-var)) in-steps (out-steps ell2 (apply step ell2 chain-rest-var))))
           ((_ (placeholder ellipsis . rest) . _)
            (syntax-error "_ ... can only be used as a final argument"))
           ((_ (placeholder . in-step) (out-step ell2) (vars ell2) . rest)
            (%chain in-step (out-step ell2 chain-var) (vars ell2 chain-var) . rest))
           ((_ (x . in-step) (out-step ell2) . rest)
            (%chain in-step (out-step ell2 x) . rest))))
       (%chain (first-step ell1) () () () ((next-step ell1) ell1) (initial-value))))))

(define-syntax chain-and
  (syntax-rules ell1 ()
    ((_ initial-value) initial-value)
    ((_ initial-value (step ell1) ell1) (chain-and initial-value _ (step ell1) ell1))
    ((_ initial-value placeholder (first-step ell1) (next-step ell1) ell1)
     (let ()
       (define-syntax %chain-and
         (syntax-rules ell2 (placeholder)
           ; (_ in-step out-step in-vars out-vars in-steps out-steps)
           ((_ () () () (var ell2) () (step ell2 last-step))
            (and-let* ((var step) ell2) last-step))
           ((_ () () () out-vars (step . in-steps) out-steps)
            (%chain-and step () () out-vars in-steps out-steps))
           ((_ () step () (out-vars ell2) in-steps (out-steps ell2))
            (%chain-and () () () (out-vars ell2 ignored) in-steps (out-steps ell2 step)))
           ((_ () step (var) (out-vars ell2) in-steps (out-steps ell2))
            (%chain-and () () () (out-vars ell2 var) in-steps (out-steps ell2 step)))
           ((_ (placeholder . in-step) (out-step ell2) () . rest)
            (%chain-and in-step (out-step ell2 chain-var) (chain-var) . rest))
           ((_ (placeholder . excess) . rest)
            (syntax-error "chain-and does not support multiple _ in a single step"))
           ((_ (x . in-step) (out-step ell2) . rest)
            (%chain-and in-step (out-step ell2 x) . rest))))
       (%chain-and (first-step ell1) () () () ((next-step ell1) ell1) (initial-value))))))

(define-syntax chain-when
  (syntax-rules ell1 ()
    ((_ initial-value) initial-value)
    ((_ initial-value (guard? (step ell1)) ell1)
     (chain-when initial-value _ (guard? (step ell1)) ell1))
    ((_ initial-value placeholder (first-guard? (first-step ell1)) (next-guard? (next-step ell1)) ell1)
     (let ()
       (define-syntax %chain-when
         (syntax-rules ell2 (placeholder)
           ; (_ in-step out-step guard? chain-var in-steps out-expr)
           ((_ () () _1 _2 () out-expr) out-expr)
           ((_ () () _1 _2 ((guard? step) . in-steps) out-expr)
            (%chain-when step () guard? #f in-steps out-expr))
           ((_ () step guard? #f in-steps out-expr)
            (%chain-when () () #f #f in-steps
                         (let ((chain-var out-expr))
                           (if guard? step chain-var))))
           ((_ () step guard? chain-var in-steps out-expr)
            (%chain-when () () #f #f in-steps
                         (let ((chain-var out-expr))
                           (if guard? step chain-var))))
           ((_ (placeholder . in-step) (out-step ell2) guard? #f . rest)
            (%chain-when in-step (out-step ell2 chain-var) guard? chain-var . rest))
           ((_ (placeholder . excess) . rest)
            (syntax-error "chain-when does not support multiple _ in a single step"))
           ((_ (x . in-step) (out-step ell2) . rest)
            (%chain-when in-step (out-step ell2 x) . rest))))
       (%chain-when (first-step ell1) () first-guard? #f ((next-guard? (next-step ell1)) ell1) initial-value)))))

(define-syntax chain-lambda
  (syntax-rules ell1 ()
    ((_ (step ell1) ell1) (chain-lambda _ ... (step ell1) ell1))
    ((_ placeholder (step ell1) ell1) (chain-lambda placeholder ... (step ell1) ell1))
    ((_ placeholder ellipsis (first-step ell1) (next-step ell1) ell1)
     (let ()
       (define-syntax %chain-lambda
         (syntax-rules ell2 (placeholder ellipsis)
           ; (_ in-step out-step args rest-of-steps)
           ((_ () step args ())
            (lambda args step))
           ((_ () step args steps)
            (lambda args
              (chain step placeholder ellipsis . steps)))
           ((_ (placeholder ellipsis) (step ell2) () ())
            (lambda chain-rest-var (apply step ell2 chain-rest-var)))
           ((_ (placeholder ellipsis) (step ell2) () steps)
            (lambda chain-rest-var
              (chain (apply step ell2 chain-rest-var) placeholder ellipsis . steps)))
           ((_ (placeholder ellipsis) (step ell2) (args ell2) ())
            (lambda (args ell2 . chain-rest-var) (apply step ell2 chain-rest-var)))
           ((_ (placeholder ellipsis) (step ell2) (args ell2) steps)
            (lambda (args ell2 . chain-rest-var)
              (chain (apply step ell2 chain-rest-var) placeholder ellipsis . steps)))
           ((_ (placeholder ellipsis . excess) . rest)
            (syntax-error "_ ... can only be used as a final argument"))
           ((_ (placeholder . in-step) (out-step ell2) (args ell2) . rest)
            (%chain-lambda in-step (out-step ell2 chain-var) (args ell2 chain-var) . rest))
           ((_ (x . in-step) (out-step ell2) . rest)
            (%chain-lambda in-step (out-step ell2 x) . rest))))
       (%chain-lambda (first-step ell1) () () ((next-step ell1) ell1))))))

(define-syntax nest
  (syntax-rules ell1 (_)
    ((nest last) last)
    ((nest (step ell1) ell1 last) (nest _ (step ell1) ell1 last))
    ((nest placeholder (extra-step ell1) ell1 (first-step ell1) last)
     (let ()
       ; let-syntax is buggy in some Schemes, define-syntax is more reliable
       (define-syntax %nest
         (syntax-rules ell2 (placeholder)
           ((%nest result () placeholder ()) result)
           ((%nest result () placeholder (rest ell2 step))
            (%nest () step result (rest ell2)))
           ((%nest result () accum steps)
            (syntax-error "nest: step must contain _"))
           ((%nest result (placeholder . rest) placeholder steps)
            (syntax-error "nest: only one _ allowed per step"))
           ((%nest (result ell2) (placeholder . rest) accum steps)
            (%nest (result ell2 accum) rest placeholder steps))
           ((%nest (result ell2) (element . rest) accum steps)
            (%nest (result ell2 element) rest accum steps))))
       (%nest () (first-step ell1) last ((extra-step ell1) ell1))))
    ((nest placeholder last) last)))

(define-syntax nest-reverse
  (syntax-rules ell1 (_)
    ((nest-reverse first) first)
    ((nest-reverse first (step ell1) ell1) (nest-reverse first _ (step ell1) ell1))
    ((nest-reverse first placeholder (first-step ell1) (extra-step ell1) ell1)
     (let ()
       (define-syntax %nest
         (syntax-rules ell2 (placeholder)
           ((%nest result () placeholder ()) result)
           ((%nest result () placeholder (step . rest))
            (%nest () step result rest))
           ((%nest result () accum steps)
            (syntax-error "nest-reverse: step must contain _"))
           ((%nest result (placeholder . rest) placeholder steps)
            (syntax-error "nest-reverse: only one _ allowed per step"))
           ((%nest (result ell2) (placeholder . rest) accum steps)
            (%nest (result ell2 accum) rest placeholder steps))
           ((%nest (result ell2) (element . rest) accum steps)
            (%nest (result ell2 element) rest accum steps))))
       (%nest () (first-step ell1) first ((extra-step ell1) ell1))))
    ((nest-reverse first placeholder) first)))
