(define-library
  (srfi 48)
  (import (scheme base)
          (scheme char)
          (scheme complex)
          (scheme write)
          (scheme r5rs)
          (srfi 38))
  (export format)
  (include "48.scm"))
