ARG COMPILE_R7RS=chibi
FROM debian:bookworm AS build
RUN apt-get update && apt-get install -y build-essential chicken-bin
RUN wget https://bitbucket.org/ktakashi/sagittarius-scheme/downloads/sagittarius-0.9.12.tar.gz && tar -xf sagittarius-0.9.12.tar.gz
RUN cd sagittarius-0.9.12 && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr/local-other .. && make && make install
RUN git clone https://github.com/Retropikzel/compile-r7rs.git --depth=1
RUN cd compile-r7rs && make && make install

FROM schemers/${COMPILE_R7RS}
COPY --from=build /usr/local/bin/compile-r7rs /usr/local/bin/compile-r7rs

