FROM debian:trixie
RUN apt-get update && apt-get install -y \
    make gcc git ca-certificates libffi-dev docker.io git
RUN git clone https://github.com/ashinn/chibi-scheme.git
WORKDIR /chibi-scheme
RUN make && make install
RUN snow-chibi install --impls=chibi retropikzel.test-r7rs
