FROM retropikzel1/compile-r7rs
RUN apt-get update && apt-get install -y gcc make libffi-dev docker.io
RUN git clone https://github.com/ashinn/chibi-scheme.git --depth=1
WORKDIR /chibi-scheme
RUN make && make install
WORKDIR /workdir
RUN mkdir -p ${HOME}/.snow && echo "()" > "${HOME}"/.snow/congig.scm
