ARG SCHEME=chibi
FROM schemers/gauche AS build
RUN apt-get update && apt-get install -y \
    build-essential \
    chicken-bin \
    ca-certificates \
    git \
    make
RUN chicken-install r7rs
RUN git clone https://github.com/Retropikzel/compile-r7rs.git --depth=1
RUN cd compile-r7rs && make && make install

FROM schemers/${SCHEME}
RUN apt-get update && apt-get install -y \
    make \
    ca-certificates \
    git
COPY --from=build /usr/local /usr/local-other
ENV PATH=/usr/local-other/bin:${PATH}
ARG SCHEME=chibi
ENV COMPILE_R7RS=${SCHEME}
