ARG COMPILE_R7RS=chibi
FROM debian:bookworm AS build
RUN apt-get update && apt-get install -y \
    build-essential \
    chicken-bin \
    ca-certificates \
    git \
    make
RUN chicken-install r7rs
RUN git clone https://github.com/Retropikzel/compile-r7rs.git --depth=1
RUN cd compile-r7rs && make && make install

FROM schemers/${COMPILE_R7RS}
COPY --from=build /usr/local/bin/compile-r7rs /usr/local/bin/compile-r7rs

