FROM retropikzel1/compile-r7rs
RUN apt-get update && apt-get install -y gcc make libffi-dev
RUN git clone https://github.com/ashinn/chibi-scheme.git --depth=1
WORKDIR /chibi-scheme
RUN make && make install
WORKDIR /workdir
ENV PATH=/opt/compile-r7rs/bin:${PATH}
