
(define implementations
  '(((name . chibi) (command . "chibi-scheme -I ."))
    ((name . chicken)
     (command . "csc -include-path ./srfi -X r7rs -R r7rs")
     (library-command . "csc -include-path ./srfi -X r7rs -R r7rs -s -J"))
    ((name . cyclone)
     (command . "cyclone -I .")
     (library-command . "cyclone -I ."))
    ((name . foment)
     (command . "foment -I --load"))
    ((name . gambit)
     (command . "gsc -exe ./ -nopreload")
     (library-command . "gsc -:search=."))
    ((name . gauche) (command . "gosh -r7 -I ."))
    ((name . gerbil)
     (command . "gxi --lang r7rs")
     (library-command . "gxc -O"))
    ((name . guile) (command . "guile --fresh-auto-compile --r7rs -L ."))
    ((name . kawa)
     (command . "kawa --r7rs -Dkawa.import.path=../../*.sld"))
    ((name . larceny)
     (command . "larceny -r7 -I ."))
    ((name . loko)
     (command . "loko -std=r7rs --compile")
     ; Library command so the executable gets run
     (library-command . "ls"))
    ((name . mit-scheme)
     (command . "mit-scheme --load")) ;; FIXME
    ((name . mosh) (command . "mosh --loadpath=."))
    ((name . racket) (command . "racket -I r7rs -S . --script"))
    ((name . sagittarius) (command . "sash -r7 -L . -L ./srfi"))
    ((name . stklos) (command . "stklos -I . -I ./srfi -f"))
    ((name . skint) (command . "skint -I ./"))
    ((name . tr7) (command . "tr7i"))
    ((name . ypsilon) (command . "ypsilon --r7rs --loadpath=."))))
