
(define implementations
  '(((name . chibi) (command . "chibi-scheme -I srfi"))
    ((name . chicken)
     (command . "csc -include-path ./srfi -X r7rs -R r7rs")
     (library-command . "csc -include-path ./srfi -X r7rs -R r7rs -s -J"))
    ((name . cyclone)
     (command . "cyclone -A .")
     (library-command . "cyclone -A ."))
    ((name . gambit)
     (command . "gsc -exe . -nopreload")
     (library-command . "gsc ."))
    ((name . gauche) (command . "gosh"))
    ((name . guile) (command . "guile --fresh-auto-compile --r7rs -L ."))
    ((name . kawa) (command . "kawa --r7rs -Dkawa.import.path=..:*.sld"))
    ((name . loko) (command . "loko -std=r7rs -feval --compile"))
    ((name . mit-scheme) (command . "mit-scheme --load"))
    ((name . sagittarius) (command . "sash -L . -r7"))
    ((name . stklos) (command . "STKLOS_FRAMES=1 stklos -I . -f"))
    ((name . skint) (command . "skint --program"))
    ((name . tr7) (command . "tr7i"))))
