;;;; srfi-8.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (scheme#eval
      '(import-syntax
         (only r7rs
               begin
               cond-expand
               export
               import
               import-for-syntax
               include
               include-ci
               syntax-rules)
         scheme.base))
    (import
      (only r7rs
            begin
            cond-expand
            export
            import
            import-for-syntax
            include
            include-ci
            syntax-rules))
    (##sys#register-compiled-module
      'srfi-8
      'srfi-8
      (scheme#list)
      '()
      (scheme#list
        (scheme#cons
          'receive
          (syntax-rules
            ()
            ((receive formals expression body ...)
             (call-with-values
               (lambda () expression)
               (lambda formals body ...)))))
        (scheme#cons
          '|\x04r7rssrfi-8|
          (##sys#er-transformer (##core#lambda (x r c) (##core#undefined)))))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
