;;;; srfi-28.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (scheme#eval
      '(import-syntax
         (only r7rs
               begin
               cond-expand
               export
               import
               import-for-syntax
               include
               include-ci
               syntax-rules)
         scheme.base
         scheme.write))
    (import
      (only r7rs
            begin
            cond-expand
            export
            import
            import-for-syntax
            include
            include-ci
            syntax-rules))
    (##sys#register-compiled-module
      'srfi-28
      'srfi-28
      (scheme#list)
      '((format . srfi-28#format))
      (scheme#list
        (scheme#cons
          '|\x04r7rssrfi-28|
          (##sys#er-transformer (##core#lambda (x r c) (##core#undefined)))))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
