;;;; srfi-26.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (scheme#eval
      '(import-syntax
         (only r7rs
               begin
               cond-expand
               export
               import
               import-for-syntax
               include
               include-ci
               syntax-rules)
         scheme.base))
    (import
      (only r7rs
            begin
            cond-expand
            export
            import
            import-for-syntax
            include
            include-ci
            syntax-rules))
    (##sys#register-compiled-module
      'srfi-26
      'srfi-26
      (scheme#list)
      '()
      (scheme#list
        (scheme#cons
          'cute
          (syntax-rules
            ()
            ((cute . slots-or-exprs)
             (srfi-26-internal-cute () () () . slots-or-exprs))))
        (scheme#cons
          'cut
          (syntax-rules
            ()
            ((cut . slots-or-exprs)
             (srfi-26-internal-cut () () . slots-or-exprs))))
        (scheme#cons
          '|\x04r7rssrfi-26|
          (##sys#er-transformer (##core#lambda (x r c) (##core#undefined)))))
      (scheme#list
        (scheme#cons
          'srfi-26-internal-cute
          (syntax-rules
            (<> <...>)
            ((srfi-26-internal-cute
               (slot-name ...)
               nse-bindings
               (proc arg ...))
             (let nse-bindings (lambda (slot-name ...) (proc arg ...))))
            ((srfi-26-internal-cute
               (slot-name ...)
               nse-bindings
               (proc arg ...)
               <...>)
             (let nse-bindings (lambda
                                (slot-name ... . x)
                                (apply proc arg ... x))))
            ((srfi-26-internal-cute
               (slot-name ...)
               nse-bindings
               (position ...)
               <>
               .
               se)
             (srfi-26-internal-cute
               (slot-name ... x)
               nse-bindings
               (position ... x)
               .
               se))
            ((srfi-26-internal-cute
               slot-names
               nse-bindings
               (position ...)
               nse
               .
               se)
             (srfi-26-internal-cute
               slot-names
               ((x nse) . nse-bindings)
               (position ... x)
               .
               se))))
        (scheme#cons
          'srfi-26-internal-cut
          (syntax-rules
            (<> <...>)
            ((srfi-26-internal-cut (slot-name ...) (proc arg ...))
             (lambda (slot-name ...) ((begin proc) arg ...)))
            ((srfi-26-internal-cut (slot-name ...) (proc arg ...) <...>)
             (lambda (slot-name ... . rest-slot)
               (apply proc arg ... rest-slot)))
            ((srfi-26-internal-cut (slot-name ...) (position ...) <> . se)
             (srfi-26-internal-cut (slot-name ... x) (position ... x) . se))
            ((srfi-26-internal-cut (slot-name ...) (position ...) nse . se)
             (srfi-26-internal-cut (slot-name ...) (position ... nse) . se)))))
      (scheme#list))))

;; END OF FILE
